# Generated by Django 3.2.5 on 2021-08-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='day_night_status',
            field=models.IntegerField(),
        ),
    ]
